### ISSUE TITLE
Trigger model creation after while.

### ISSUE THREAD

**Issue by mladvladimir** [oxtopus/skeleton-htmengine-app#11]
Hi,

I'm trying to figure out how to trigger model creation after sending data without specifying min/max values for model, according to docs:

> to omit the min and max and let htmengine choose a value based on the history of a metric 

PUT request with empty JSON still gives NULL for anomaly value and status code 8 in 'metric' table in mysql. Can you please provide some an example.

ps. All command examples and python scripts mentioned in README.md are working ok in my installation.

I am new in htmengine and NUPIC.
Thanks in advance
Vladimir

**Comment by rhyolight** [comment]
@mladvladimir Did you pass data into the HTTP API before creating the model? 

CC @oxtopus @vitaly-krugl

**Comment by vitaly-krugl** [comment]
When you try to promote a custom metric to model without passing min/max, the logic places the model in "PENDING DATA" (status=8) state if the number of metric data rows for this metric is less than MODEL_CREATION_RECORD_THRESHOLD (288); once at least MODEL_CREATION_RECORD_THRESHOLD data rows become available, htmengine will automatically complete the promotion of metric to model.  If there are at least `MODEL_CREATION_RECORD_THRESHOLD` rows, then the [Custom Datasource Adapter gets min/max from the data](https://github.com/numenta/numenta-apps/blob/28b9bfa71181ebf02fda29441ff99d7d94c98923/htmengine/htmengine/adapters/datasource/custom/__init__.py#L309), enabling the model to proceed directly to `CREATE_PENDING` state, which will lead to the `ACTIVE` state once the "define model" command is processed by [Model Runner](https://github.com/numenta/numenta-apps/blob/32018f5b8658c29e7c33ac819da85a0bda706bd0/htmengine/htmengine/model_swapper/model_runner.py#L363) and its result is processed by [Anomaly Service](https://github.com/numenta/numenta-apps/blob/1ff572a21a5c27fd290822e572ce33f42e1ee19e/htmengine/htmengine/runtime/anomaly_service.py#L250).

Note that Anomaly Service is primarily responsible for calculating the Anomaly Likelihood scores, and also handles the "defineModel" and "deleteModel" commands.

The metric status (state) values are defined here: https://github.com/numenta/numenta-apps/blob/28b9bfa71181ebf02fda29441ff99d7d94c98923/htmengine/htmengine/repository/queries.py#L35

**Comment by vitaly-krugl** [comment]
In the Taurus (HTM for Stocks) application, we created a service that - among other things - periodically checks metric data row counts and promotes custom metrics to rows based on a higher threshold count. See [_promoteReadyMetricsToModels ](https://github.com/numenta/numenta-apps/blob/15edc6bd5eb2cee45ba42c8d8428c1a3fbcb7047/taurus_metric_collectors/taurus_metric_collectors/common_services/metric_maintenance_agent.py#L174).

**Comment by vitaly-krugl** [comment]
There is also a new feature https://github.com/numenta/numenta-apps/blob/28b9bfa71181ebf02fda29441ff99d7d94c98923/htmengine/htmengine/adapters/datasource/custom/__init__.py#L285 that allows you to pass complete model params, thus bypassing the `MODEL_CREATION_RECORD_THRESHOLD` check.

To use this feature, pass the [completeModelParams](https://github.com/ryanjmccall/numenta-apps/blob/4cb71aff522418deec5e3c9304a39040c54cfdbb/htmengine/htmengine/adapters/datasource/model_spec_schema.json#L36) property instead of the modelParams property in the JSON arg.

**Comment by rhyolight** [comment]
Many thanks @vitaly-krugl. Does this help you, @mladvladimir?

**Comment by mladvladimir** [comment]
@vitaly-krugl @rhyolight It works, thank you very much for detailed explanation.
