### ISSUE TITLE
htmengine install error

### ISSUE THREAD

**Issue by scaviator** [oxtopus/skeleton-htmengine-app#18]
Hello,

I'm trying to install the prereq for the skeleton app; however, I can't seem to install the htmengine.  I installed nupic (1.0.6) and nta.utils with no issues, but when I try to install the htmengine:

> 
_configtest.c:1:5: warning: conflicting types for built-in function âexpâ
 int exp (void);
     ^
_configtest.o: In function `main':
/tmp/easy_install-T0XsKE/numpy-1.9.2/_configtest.c:6: undefined reference to `exp'
collect2: error: ld returned 1 exit status
_configtest.c:1:5: warning: conflicting types for built-in function âexpâ
 int exp (void);
     ^
_configtest.c:4:5: warning: function declaration isnât a prototype [-Wstrict-prototypes]
 int main()
     ^
_configtest.c:4:5: warning: function declaration isnât a prototype [-Wstrict-prototypes]
 int main()
     ^
_configtest.c:4:5: warning: function declaration isnât a prototype [-Wstrict-prototypes]
 int main()
     ^
_configtest.c:4:5: warning: function declaration isnât a prototype [-Wstrict-prototypes]
 int main()
     ^
_configtest.c:3:5: warning: function declaration isnât a prototype [-Wstrict-prototypes]
 int main ()
     ^
_configtest.c: In function âmainâ:
_configtest.c:5:16: warning: variable âtest_arrayâ set but not used [-Wunused-but-set-variable]
     static int test_array [1 - 2 * !(((long) (sizeof (npy_check_sizeof_type))) >= 0)];
                ^
_configtest.c:3:5: warning: function declaration isnât a prototype [-Wstrict-prototypes]
 int main ()
     ^
_configtest.c: In function âmainâ:
_configtest.c:5:16: warning: variable âtest_arrayâ set but not used [-Wunused-but-set-variable]
     static int test_array [1 - 2 * !(((long) (sizeof (npy_check_sizeof_type))) == 4)];
                ^
_configtest.c:3:5: warning: function declaration isnât a prototype [-Wstrict-prototypes]
 int main ()
     ^
_configtest.c: In function âmainâ:
_configtest.c:5:16: warning: variable âtest_arrayâ set but not used [-Wunused-but-set-variable]

> 

Does anybody know if nupic 1.0.6 is compatible with the htmengine?
My environment is Ubuntu 16.04 LTS.

**Comment by rhyolight** [comment]
This would be an HTM Engine issue, but it has no issue tracker because it is in maintenance mode. ☹️

**Comment by scaviator** [comment]
See this issue # on how to resolve this issue.

https://github.com/numenta/nupic/issues/3848
